### ISSUE TITLE
infinite loop with 404 pages

### ISSUE THREAD

**Issue by flexbox** [leanjs/leanjs#120]
As a user
I can have some hint on the error page
So that visit the website

---
If you try https://reactjs.academy/setup there is an infinite loop.

Just add a simple page with 2 links
- Homepage
- Read the blog

Example: https://davidl.fr/setup

**Comment by StudioSpindle** [comment]
Quite a while since this issue was opened. Has this been resolved?

**Comment by flexbox** [comment]
@StudioSpindle Thank you for the feedback
Yes we solved the issue a long time ago :)
