### ISSUE TITLE
the yarn test need a yarn build

### ISSUE THREAD

**Issue by luciopalmieri** [leanjs/leanjs#262]
Hi @alexlbr , following the setup in https://github.com/leanjs/leanjs/blob/main/docs/contributing.md, I've run 

```
git clone https://github.com/luciopalmieri/leanjs-fork.git 
cd leanjs-fork
yarn
yarn test
```

receiving this error:

```
> @leanjs/tests-react-17@0.0.1 test
> jest

 FAIL  src/createRuntimeBindings.test.tsx
  ● Test suite failed to run

    Cannot find module '@leanjs/core' from 'src/createRuntimeBindings.test.tsx'
```

for now i solved by doing a build before the tests so that the compiled module is found:

```
git clone https://github.com/luciopalmieri/leanjs-fork.git 
cd leanjs-fork
yarn
yarn build
yarn test
```

I find your project very interesting and I started experimenting with it, perhaps hoping to be able to make some contributions as well

regards,
Lucio

**Comment by alexlbr** [comment]
Thanks for trying LeanJS @luciopalmieri. You're right, we have to `build` it before we can `test`.  Do you want to create a PR to fix that in the contributing page? That'd could be a small first contribution 😉. Happy to have chat if you're also interested in more challenging contributions 🙂

**Comment by alexlbr** [comment]
fixed by https://github.com/leanjs/leanjs/pull/263

**Comment by luciopalmieri** [comment]
> Thanks for trying LeanJS @luciopalmieri. You're right, we have to `build` it before we can `test`. Do you want to create a PR to fix that in the contributing page? That'd could be a small first contribution 😉. Happy to have a chat if you're also interested in more challenging contributions 🙂

Sure, I'd love to, feel free to contact me on twitter: @lucio_palmieri
