### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by AlexTraher** [leanjs/leanjs#31]
Hey,

I've been following the progress of leanjs since the CityJS talk and wanted to ask if you were open to contributions? 

I'm sure there is a long list of things to do and I'd love to be involved!

(Apologies if this isn't the right place to raise this)

Cheers

**Comment by alexlbr** [comment]
Hi @AlexTraher! Good to hear from you. Thanks a lot for your message and interest in helping out. Yes, we are open to contributions :D. I've sent you a Twitter DM to discuss further.
